apiVersion: v1
kind: Service
metadata:
  name: otel-gateway
spec:
  type: ClusterIP
  selector: { app: otel-gateway }
  ports:
    - { name: otlp-grpc, port: 4317, targetPort: otlp-grpc }
    - { name: otlp-http, port: 4318, targetPort: otlp-http }
